### ISSUE TITLE
Expression selection should respond to operators in a mathematically meaningful way

### ISSUE THREAD

**Issue by acpiplica** [apollo-ctp/mathquill#1]
We would like to constrain math selection to be mathematically meaningful. One aspect of mathematically meaningful selection is how operators are bound to their operands in selection. For example, we do not consider it mathematically meaningful to select just an operator by itself in an expression. The following rules are a first pass for enforcing mathematically meaningful selection of binary operators in expressions (this does not include relational operators):
* A binary operator cannot be selected by itself. The selection must at least contain the term following the operator.
  * This rule is sufficient to constrain selection of minus and plus-or-minus, because they can also be unary sign operators.
* Other binary operators (+, *, //) must be selected with both of their operands.
* In a polynomial expression, if the first term of the selection is preceded by a minus, the minus must be included in the selection. For example, in x-8+8, "8+8" is not a valid selection but "-8+8" is.

**Comment by acpiplica** [comment]
Strict operator selection (#16) addresses "mathematically meaningful" selection as described here.

**Comment by kschaefe** [comment]
Pulled #16.
